# Generated by Django 4.2.30 on 2026-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_boxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftbox',
            name='max_items',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of products allowed in this box'),
        ),
    ]
