# Generated by Django 6.0.4 on 2026-04-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0004_productvarianttype_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariantsku'),
        ),
    ]
