# Generated by Django 6.0.4 on 2026-04-21 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_subscribers_only_wishlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Variant Type',
                'verbose_name_plural': 'Product Variant Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='variant_config', to='products.product')),
                ('variant_types', models.ManyToManyField(related_name='products', to='products.productvarianttype')),
            ],
            options={
                'verbose_name': 'Product Variant Config',
                'verbose_name_plural': 'Product Variant Configs',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variant_values/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productvarianttype')),
            ],
            options={
                'verbose_name': 'Product Variant Value',
                'verbose_name_plural': 'Product Variant Values',
                'ordering': ['order', 'value'],
                'unique_together': {('variant_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_skus', to='products.product')),
                ('variant_values', models.ManyToManyField(related_name='skus', to='products.productvariantvalue')),
            ],
            options={
                'verbose_name': 'Product Variant SKU',
                'verbose_name_plural': 'Product Variant SKUs',
                'ordering': ['sku'],
            },
        ),
    ]
