# Generated by Django 6.0.4 on 2026-04-21 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvarianttype_productvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantsku',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariantsku',
            name='short_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='productvariantsku',
            name='size_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariantsku',
            name='size_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
