# Generated by Django 4.2.30 on 2026-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_new_arrival_seasonalkit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalkit',
            name='badge',
            field=models.CharField(blank=True, help_text='Short badge label shown on card, e.g. "Summer Edition"', max_length=80),
        ),
    ]
